services:
  extlatency-web:
    image: nginx:latest
    expose:
      - 80
    volumes:
      - ./build:/usr/share/nginx/html # run build first
    labels:
      - traefik.enable=true
      - traefik.http.routers.extlatency.entrypoints=websecure
      - traefik.http.routers.extlatency.tls.certresolver=letsencryptresolver
      - traefik.http.routers.extlatency.rule=Host(`extlatency.${DOMAIN}`)
    networks:
      - default
      - web
networks:
  web:
    external: true